---
# Defines the port channels and bind interfaces for these uplinks

- name: Create UCS Port Channels
  cisco.ucs.ucs_managed_objects:
    objects:
    - module: ucsmsdk.mometa.fabric.FabricEthLanPc
      class: FabricEthLanPc
      properties:
        name: "{{ item.name }}"
        port_id: "{{ item.port_id }}"
        parent_mo_or_dn: "fabric/lan/{{ item.switch_id }}"
        admin_state: "{{ item.admin_state }}"
    state: "{{ item.state }}"
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ lacp_interfaces }}"

- name: Configure Network Interfaces for UCS Port Channels
  cisco.ucs.ucs_managed_objects:
    objects:
      - module: ucsmsdk.mometa.ether.EtherPIo
        class: EtherPIo
        properties:
          port_id: "{{ item.port_id }}"
          parent_mo_or_dn: "sys/switch-{{ item.switch_id }}/slot-{{ item.slot_id }}/switch-ether"
    state: "{{ item.state }}"
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ lacp_members }}"

- name: Assign interfaces to UCS Port Channels
  cisco.ucs.ucs_managed_objects:
    objects:
    - module: ucsmsdk.mometa.fabric.FabricEthLanPcEp
      class: FabricEthLanPcEp
      properties:
        slot_id: "{{ item.slot_id }}"
        port_id: "{{ item.port_id }}"
        parent_mo_or_dn: "fabric/lan/{{ item.switch_id }}/pc-{{ item.pc_id }}"
    state: "{{ item.state }}"
    hostname: "{{ this_ucs_hostname }}"
    username: "{{ this_ucs_username }}"
    password: "{{ this_ucs_password }}"
  loop: "{{ lacp_members }}"
