---
# Default values specific to creating VPCs.  Default values.

fabric_vlans:
  - vlan_id: 999
    vlan_name: "default"
    ucs_fabric: "common"
    native_vlan: "no"
    state: present
    enabled: true

# group_vars
vpc_domain_common:
  domain: 10
  system_priority: 2000
  delay_restore: 150
  delay_restore_interface_vlan: 10
  delay_restore_orphan_port: 0
  auto_recovery: yes
  auto_recovery_reload_delay: 240
  peer_gw: no
  state: present

# host_vars
vpc_domain_local:
  role_priority: 1000
  pkl_vrf: 'management'
  pkl_src: 1.1.1.1
  pkl_dest: 2.2.2.2  

# group_vars
vpc_intf_common:
  - vpc: peer_link
    portchannel: 100
    description: "VPC Peer Link"
    type: layer2
    mode: trunk
    native_vlan: 2
    allowed_vlans: all
    state: present
  - vpc: 11
    portchannel: 11
    description: "Port Channel 11"
    type: layer2
    mode: trunk
    native_vlan: 2
    state: present
  - vpc: 21
    portchannel: 21
    description: "Port Channel 21"
    type: layer2
    mode: access
    native_vlan: 2
    state: present

# host_vars
vpc_intf_local:
  - name: port-channel100
    members:
      - member: Ethernet1/53
        mode: active
      - member: Ethernet1/54
        mode: active
  - name: port-channel11
    members:
      - member: Ethernet1/1
        mode: active
  - name: port-channel21
    members:
      - member: Ethernet1/2
        mode: active
