---
# Create and manage the VPC Domain

# Enable the VPC feature
- name: Enable VPC features
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop:
    - lacp
    - vpc

# Create the VPC Domain
- name: Create NXOS VPC Domain
  cisco.nxos.nxos_vpc:
    state: "{{ vpc_domain_common.state }}"
    domain: "{{ vpc_domain_common.domain }}"
    system_priority: "{{ vpc_domain_common.system_priority | default(omit) }}"
    delay_restore: "{{ vpc_domain_common.delay_restore | default(omit) }}"
    delay_restore_interface_vlan: "{{ vpc_domain_common.delay_restore_interface_vlan | default(omit) }}"
    delay_restore_orphan_port: "{{ vpc_domain_common.delay_restore_orphan_port | default(omit) }}"
    auto_recovery: "{{ vpc_domain_common.auto_recovery | default(omit) }}"
    auto_recovery_reload_delay: "{{ vpc_domain_common.auto_recovery_reload_delay | default(omit) }}"
    peer_gw: "{{ vpc_domain_common.peer_gw | default(omit) }}"
    role_priority: "{{ item.role_priority | default(omit) }}"
    pkl_vrf: "{{ item.pkl_vrf | default(omit) }}"
    pkl_src: "{{ item.pkl_src | default(omit) }}"
    pkl_dest: "{{ item.pkl_dest | default(omit) }}"
  loop: "{{ vpc_domain_local }}"
