---
# file: nxos/defaults/main.yaml

# Default variables needed for this role.  Please note, that other roles
# may reference the same variables and so these should be defined at a
# higher precedence that role/defaults (such as host group)

fabric_vlans:
  - vlan_id: 999
    vlan_name: "default"
    ucs_fabric: "common"
    native_vlan: "no"
    state: present
    enabled: true
