---
# file: export-single.yaml

- hosts: localhost
  become: false
  gather_facts: true
  connection: local

# example: ansible-playbook export-single.yaml -e 'switch=fabric2-spine1'
- hosts: '{{ switch }}'
  gather_facts: false
  collections:
    - gve_vse_tim.ansible_cisco_datacenter
  vars:
    my_date_time: "{{ hostvars['localhost']['ansible_date_time']['date'] }}"
    export_directory: "./"
  roles:
    - role: nxos/export_config
  