---
# file: main.yaml

# Export the running config to the ansible client
- name: Export running config to Ansible client (running.{{ my_date_time }})
  nxos_config:
    backup: yes
    backup_options:
      dir_path: "{{ export_directory }}"
      filename: "{{ inventory_hostname }}_running_{{ my_date_time }}.cfg"
